<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'local_checksummer', language 'en'.
 *
 * @package    local_checksummer
 * @copyright  2026 onwards Louisiana State University
 * @copyright  2026 onwards Robert Russo
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'Checksummer';
$string['task_run_checksummer'] = 'Run checksummer task';
$string['mode'] = 'Mode';
$string['mode_desc'] = 'Select the mode for the checksummer: Generate (create a manifest of the directory) or Compare (compare the directory against a source manifest).';
$string['mode_generate'] = 'Generate';
$string['mode_compare'] = 'Compare';
$string['directory'] = 'Directory';
$string['directory_desc'] = 'The absolute path to the directory to process.';
$string['timeout'] = 'Timeout Limit';
$string['timeout_desc'] = 'The maximum time (in minutes) an adhoc task will run before it pauses and schedules a continuation task for the next cron cycle.';
$string['settings'] = 'Checksummer Settings';
$string['schedule_task'] = 'Schedule Task';
$string['schedule_task_desc'] = 'Schedule an adhoc task to run the checksummer with the current settings.';
$string['task_scheduled'] = 'Task successfully scheduled.';
$string['generated_files'] = 'Generated Files';
$string['generated_files_desc'] = 'Download or delete manifests and reports generated by the task.';
$string['uploaded_files'] = 'Source Manifests (Compare Mode)';
$string['uploaded_files_desc'] = 'Upload source manifests to compare against when running in Compare mode.';
$string['upload_manifest'] = 'Upload Source Manifest';
$string['download'] = 'Download';
$string['delete'] = 'Delete';
$string['file_deleted'] = 'File successfully deleted.';
$string['file_not_found'] = 'File not found.';
$string['no_files'] = 'No files found.';
$string['upload_form'] = 'Upload Manifest Form';
$string['file'] = 'Manifest File';
$string['save'] = 'Save';
$string['error_upload'] = 'Error saving uploaded file.';
$string['upload_success'] = 'File successfully uploaded.';
$string['file_name_req'] = 'Output filename (without extension)';
$string['file_name_req_desc'] = 'Name of the output file that will be generated (e.g. "my_manifest" or "my_report"). The .csv extension is added automatically.';
$string['source_manifest'] = 'Source Manifest';
$string['source_manifest_desc'] = 'Select the source manifest to compare against (must be uploaded first).';
$string['actions'] = 'Actions';
