language: php

os: linux

dist: xenial

notifications:
  email: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  postgresql: "9.6"

php:
  - "7.2"
  - "7.3"
  - "7.4"

env:
  jobs:
    - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE NODEJS=14.5
    - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE NODEJS=14.5

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - if [ -n "$GITHUB_APITOKEN" ]; then composer global config github-oauth.github.com $GITHUB_APITOKEN; fi
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
#  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
